// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/prime.proto

package ru.mipt.java2017.hw2;

public final class SumPrimesProto {
  private SumPrimesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_mipt_java2017_hw2_SumRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_mipt_java2017_hw2_SumRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_mipt_java2017_hw2_SumReply_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ru_mipt_java2017_hw2_SumReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026main/proto/prime.proto\022\024ru.mipt.java20" +
      "17.hw2\"(\n\nSumRequest\022\r\n\005start\030\001 \002(\003\022\013\n\003e" +
      "nd\030\002 \002(\003\"\027\n\010SumReply\022\013\n\003sum\030\001 \002(\0032\\\n\006Wor" +
      "ker\022R\n\014CalculateSum\022 .ru.mipt.java2017.h" +
      "w2.SumRequest\032\036.ru.mipt.java2017.hw2.Sum" +
      "Reply\"\000B(\n\024ru.mipt.java2017.hw2B\016SumPrim" +
      "esProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ru_mipt_java2017_hw2_SumRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_mipt_java2017_hw2_SumRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ru_mipt_java2017_hw2_SumRequest_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_ru_mipt_java2017_hw2_SumReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_mipt_java2017_hw2_SumReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ru_mipt_java2017_hw2_SumReply_descriptor,
        new java.lang.String[] { "Sum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
