// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/prime.proto

package ru.mipt.java2017.hw2;

/**
 * Protobuf type {@code ru.mipt.java2017.hw2.SumReply}
 */
public final class SumReply extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ru.mipt.java2017.hw2.SumReply)
    SumReplyOrBuilder {
  // Use SumReply.newBuilder() to construct.
  private SumReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private SumReply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final SumReply defaultInstance;
  public static SumReply getDefaultInstance() {
    return defaultInstance;
  }

  public SumReply getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private SumReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            sum_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.mipt.java2017.hw2.SumPrimesProto.internal_static_ru_mipt_java2017_hw2_SumReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.mipt.java2017.hw2.SumPrimesProto.internal_static_ru_mipt_java2017_hw2_SumReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.mipt.java2017.hw2.SumReply.class, ru.mipt.java2017.hw2.SumReply.Builder.class);
  }

  public static com.google.protobuf.Parser<SumReply> PARSER =
      new com.google.protobuf.AbstractParser<SumReply>() {
    public SumReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SumReply(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<SumReply> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int SUM_FIELD_NUMBER = 1;
  private long sum_;
  /**
   * <code>required int64 sum = 1;</code>
   */
  public boolean hasSum() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int64 sum = 1;</code>
   */
  public long getSum() {
    return sum_;
  }

  private void initFields() {
    sum_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasSum()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, sum_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, sum_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static ru.mipt.java2017.hw2.SumReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.mipt.java2017.hw2.SumReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.mipt.java2017.hw2.SumReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.mipt.java2017.hw2.SumReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.mipt.java2017.hw2.SumReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ru.mipt.java2017.hw2.SumReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ru.mipt.java2017.hw2.SumReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ru.mipt.java2017.hw2.SumReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ru.mipt.java2017.hw2.SumReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ru.mipt.java2017.hw2.SumReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(ru.mipt.java2017.hw2.SumReply prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.mipt.java2017.hw2.SumReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.mipt.java2017.hw2.SumReply)
      ru.mipt.java2017.hw2.SumReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.mipt.java2017.hw2.SumPrimesProto.internal_static_ru_mipt_java2017_hw2_SumReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.mipt.java2017.hw2.SumPrimesProto.internal_static_ru_mipt_java2017_hw2_SumReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.mipt.java2017.hw2.SumReply.class, ru.mipt.java2017.hw2.SumReply.Builder.class);
    }

    // Construct using ru.mipt.java2017.hw2.SumReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      sum_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.mipt.java2017.hw2.SumPrimesProto.internal_static_ru_mipt_java2017_hw2_SumReply_descriptor;
    }

    public ru.mipt.java2017.hw2.SumReply getDefaultInstanceForType() {
      return ru.mipt.java2017.hw2.SumReply.getDefaultInstance();
    }

    public ru.mipt.java2017.hw2.SumReply build() {
      ru.mipt.java2017.hw2.SumReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ru.mipt.java2017.hw2.SumReply buildPartial() {
      ru.mipt.java2017.hw2.SumReply result = new ru.mipt.java2017.hw2.SumReply(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.sum_ = sum_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.mipt.java2017.hw2.SumReply) {
        return mergeFrom((ru.mipt.java2017.hw2.SumReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.mipt.java2017.hw2.SumReply other) {
      if (other == ru.mipt.java2017.hw2.SumReply.getDefaultInstance()) return this;
      if (other.hasSum()) {
        setSum(other.getSum());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasSum()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.mipt.java2017.hw2.SumReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.mipt.java2017.hw2.SumReply) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long sum_ ;
    /**
     * <code>required int64 sum = 1;</code>
     */
    public boolean hasSum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 sum = 1;</code>
     */
    public long getSum() {
      return sum_;
    }
    /**
     * <code>required int64 sum = 1;</code>
     */
    public Builder setSum(long value) {
      bitField0_ |= 0x00000001;
      sum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 sum = 1;</code>
     */
    public Builder clearSum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sum_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ru.mipt.java2017.hw2.SumReply)
  }

  static {
    defaultInstance = new SumReply(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ru.mipt.java2017.hw2.SumReply)
}

